name: docs

on:
  push:
    branches: [ 'docs*' ]
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Generate cmd docs
        run: make docs
      - name: Run mkdocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: timoni.sh
          CONFIG_FILE: mkdocs.yml
